blog5/urls.py
from django.urls import path
from . import views

app_name = 'blog5'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('detail/<int:article_id>/comment', views.comment, name='comment'),
]

project5/urls.py
from django.contrib import admin
from . import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog5.urls')),
    path('blog5/', include('blog5.urls')),
    path('markdownx/', include('markdownx.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog5/models.py
from django.db import models
from django.utils import timezone
from markdownx.utils import markdownify
from markdownx.models import MarkdownxField
import datetime
import pytz


class Category(models.Model):
    category = models.CharField('カテゴリー', max_length=25)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.category


class Tag(models.Model):
    tag = models.CharField('タグ', max_length=25)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.tag


class Article(models.Model):
    title = models.CharField('title', max_length=40)
    summary = models.CharField('summary', max_length=100, default="test")
    content = MarkdownxField('content', max_length=5000)
    image = models.ImageField(upload_to='documents/', default='defo.jpg')
    created_at = models.DateTimeField('date', default=timezone.now)
    category = models.ForeignKey(Category, verbose_name='カテゴリー', default=11, on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)

    def get_days_ago(self):
        now = datetime.datetime.now()
        timezone = pytz.timezone('Asia/Tokyo')
        now = timezone.localize(now)
        delta = now - self.created_at
        return delta.days

    def text_to_markdown(self):
        return markdownify(self.content)

    def __str__(self):
        return self.title


class Comment(models.Model):
    comment = models.TextField('コメント', max_length=300)
    name = models.CharField('名前', max_length=20, default="")
    mailadress = models.EmailField('メール', max_length=30, blank=True)
    article = models.ForeignKey(Article, verbose_name='親記事', on_delete=models.PROTECT, default=11)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.comment



# Create your models here.

blog5/forms.py
from django import forms
from .models import Comment

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'mailadress', 'comment')

blog5/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect, render
from django.urls import reverse_lazy
from .models import Article, Category, Tag, Comment
from django.db.models import Q
from .forms import CommentCreateForm
import datetime

# トップページ
class IndexView(generic.ListView):
    model = Article
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'category_list': Category.objects.order_by('created_at'),
            'current_articles': Article.objects.order_by('-created_at'),
            'tag_list': Tag.objects.order_by('created_at'),
        })
        return context
    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword)|Q(content__icontains=keyword)
            )
        return queryset

# 記事の詳細ページ
class DetailView(generic.DetailView):
    model = Article
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'category_list': Category.objects.order_by('created_at'),
            'article_list': Article.objects.all().order_by('-created_at'),
            'current_articles': Article.objects.order_by('-created_at'),
            'tag_list': Tag.objects.order_by('created_at'),
            'form': CommentCreateForm()
        })
        return context

# カテゴリー絞り込み
class CategoryView(generic.ListView):
    model = Article
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'category_list': Category.objects.order_by('created_at'),
            'current_articles': Article.objects.order_by('-created_at'),
            'tag_list': Tag.objects.order_by('created_at'),
        })
        return context

    def get_queryset(self):
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Article.objects.order_by('-created_at').filter(category_id=category.id)
        return queryset

# タグ絞り込み
class TagView(generic.ListView):
    model = Article
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'category_list': Category.objects.order_by('created_at'),
            'current_articles': Article.objects.order_by('-created_at'),
            'tag_list': Tag.objects.order_by('created_at'),
        })
        return context

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs['pk'])
        queryset = tag.article_set.all().order_by('-created_at')
        return queryset

def comment(request, article_id):
    form = CommentCreateForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        article_pk = article_id
        comment = form.save(commit=False)
        comment.article_id = article_pk
        comment.save()
        return redirect('blog5:detail', pk=article_pk)

    context = {
        'form':form
    }
    return render(request, 'root', context)

blog5/templates/blog5/article_detail.html
{% extends 'blog5/base.html' %}
{% load widget_tweaks %}
{% load humanize %}
{% block headtitle %}{{ article.title }}{% endblock %}
{% block title %}{{ block.super }} - {{ article.title }}{% endblock %}
{% block summary %}{{ article.content }}{% endblock %}
{% block img %}{{ article.image.url}}{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Latest Posts -->
    <main class="post blog-post col-lg-8">
      <div class="container">
        <div class="post-single">
          <div class="post-details">
            <div class="post-meta d-flex justify-content-between">
              <div class="category">
                <a href="{% url 'blog5:category' article.category.pk %}">{{ article.category.category }}</a>
              </div>
            </div>
            <h1>{{ article.title }}</h1>
            <div class="post-footer d-flex align-items-center flex-column flex-sm-row">
              <div class="d-flex align-items-center flex-wrap">
                <div class="date">
                  <i class="icon-clock"></i>
                  {{ article.created_at|naturaltime }}
                </div>
                <!-- <div class="views"><i class="icon-eye"></i> 500</div>  閲覧数 -->
                <div class="comments meta-last">
                  <i class="icon-comment"></i>{{ artcile.comment_set.all|length }}
                </div>
              </div>
            </div>
            <div class="post-body" style="list-style-position:inside">
              {{ article.text_to_markdown | safe }}
            </div>
            <!-- タグ -->
            <div class="post-tags">
              {% for tag in article.tag.all %}
              <a href="{% url 'blog5:tag' tag.pk %}" class="tag">#{{ tag }}</a>
              {% endfor %}
            </div>
            {% include 'blog5/modules/mooving.html' %}
            {% include 'blog5/modules/comments.html' %}
            {% include 'blog5/modules/comment_form.html' %}
          </div>
        </div>
      </main>
      {% include 'blog5/modules/aside.html' %}
    </div>
  </div>
</div>
{% include 'blog5/modules/footer.html' %}
{% endblock %}

blog5/templates/blog5/article_list.html
{% extends 'blog5/base.html' %}
{% block headtitle %}{{ block.super }}{% endblock %}
{% block title %}{{ block.super }}{% endblock %}
{% block summary %}{{ block.super }}{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <main class="posts-listing col-lg-8">
      <div class="container">
        <div class="row">
          {% for article in article_list %}
            {% include 'blog5/modules/card.html' %}
          {% endfor %}
        </div>
        {% include 'blog5/modules/paginate.html' %}
      </div>
    </main>
    {% include 'blog5/modules/aside.html' %}
  </div>
</div>
{% include 'blog5/modules/footer.html' %}
{% endblock %}

blog5/templates/blog5/base.html
<!doctype html>
<html lang="ja">
{% load static %}
  <head prefix="og: http://ogp.me/ns# website: http://ogp.me/ns/website#">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- OGP -->
    <title>{% block headtitle %}Shunka's Blog{% endblock %}</title>
    <meta name="description" content="プログラミングや日常のことなどを気ままに投稿します。">
    <meta property="og:title"       content="{% block title %}Shunka's Blog{% endblock %}">
    <meta property="og:description" content="{% block summary %}プログラミングや日常のことなどを気ままに投稿します。{% endblock %}" />
    <meta property="og:type"        content="article" />
    <meta property="og:url"         content="{{ request.build_absolute_uri }}" />
    <meta property="og:image"       content="{% block img %}{% static 'img/defo.jpg' %}{% endblock %}" />
    <!-- <meta property="fb:app_id"      content="1234567890123456" /> -->
    <meta name="twitter:card"       content="summary_large_image" />
    <meta name="twitter:site"       content="@shunke428609" />
    <!-- OGP END -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.blue.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/dracula.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>
  <body>
      {% include 'blog5/modules/header.html' %}
      {% block content %}
      {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>

blog5/templates/blog5/modules/aside.html
{% load static %}
<aside class="col-lg-4">
  <!-- Widget [Search Bar Widget]-->
  <div class="widget search">
    <header>
      <h3 class="h6">
        <i class="fa fa-user" aria-hidden="true"></i>
        プロフィール
      </h3>
    </header>
    <p style='font-size:14px'>
      <img src="{% static "img/mog.png" %}" alt="..." class="img-fluid rounded-circle col-sm-3">
      <span style="font-size:18px; font-weight:bold">Shunka</span><br><br>
      エンジニア目指してプログラミングスクール通ってます。
      メガバンク、不動産会社で仕事をしていたこともあります。
      趣味は音楽、好きな食べ物はスパイスカレーです。</br>
      5/12(日) After Hours行きます。今年はサマソニも行きたい。
    <p>
  </div>
  <div class="widget search">
    <header>
      <h3 class="h6">
        <i class="fa fa-rss" aria-hidden="true"></i>
        ブログ内検索
      </h3>
    </header>
    <form action="{% url 'blog5:index' %}" class="search-form" method="GET">
      <div class="form-group">
        <input type="search" placeholder="キーワード" name="keyword">
        <button type="submit" class="submit"><i class="icon-search"></i></button>
      </div>
    </form>
  </div>
  <!-- Widget [Latest Posts Widget]        -->
  <div class="widget latest-posts">
    <header>
      <h3 class="h6">
        <i class="fa fa-newspaper-o" aria-hidden="true"></i>
        最近の投稿
      </h3>
    </header>
    {% for current_article in current_articles|slice:":5"%}
    {% include 'blog5/modules/current-post.html' %}
    {% endfor %}
  </div>
  <!-- Widget [Categories Widget]-->
  <div class="widget categories">
    <header>
      <h3 class="h6">
        <i class="fa fa-list-ul" aria-hidden="true"></i>
        カテゴリー
      </h3>
    </header>
    {% for category in category_list %}
    <div class="item d-flex justify-content-between">
      <a href="{% url 'blog5:category' category.pk %}">{{ category.category }}</a>
      <span>{{ category.article_set.all|length }}</span>
    </div>
    {% endfor %}
  </div>
  <!-- Widget [Tags Cloud Widget]-->
  <div class="widget tags">
    <header>
      <h3 class="h6">
        <i class="fa fa-tags" aria-hidden="true"></i>
        タグ
      </h3>
    </header>
    <ul class="list-inline">
      <!-- タグ -->
      {% for tag in tag_list %}
      <li class="list-inline-item"><a href="{% url 'blog5:tag' tag.pk %}" class="tag">#{{ tag.tag }}</a></li>
      {% endfor %}
    </ul>
  </div>
</aside>

blog5/templates/blog5/modules/card.html
<!-- post             -->
{% load humanize %}
<div class="post col-xl-6 border-left border-right" style="margin-left:-1px">
  <div class="post-thumbnail" style="text-align:center; background-color:black">
    <a href="{% url 'blog5:detail' article.pk %}">
     <img src="{{ article.image.url }}" alt="..." class="img-fluid" style="height:240px">
   </a>
  </div>
  <div class="post-details">
    <div class="post-meta d-flex justify-content-between">
      <div class="date meta-last">
        {{ article.created_at|date:"Y-m-j H:i:s" }}
      </div>
      <div class="category">
        <a href="{% url 'blog5:category' article.category.pk %}">
          {{ article.category.category }}
        </a>
      </div>
    </div>
    <a href="{% url 'blog5:detail' article.pk %}">
      <h3 class="h4">
        {{ article.title }}
      </h3>
    </a>
    <p class="text-muted">
      {{ article.summary }}
    </p>
    <div class="post-footer d-flex align-items-center">
      <a href="#" class="author d-flex align-items-center flex-wrap">
      <div class="date">
        <i class="icon-clock"></i>
        {{ article.created_at|naturaltime }}
      </div>
      <div class="comments meta-last">
        <i class="icon-comment"></i>
        {{ article.comment_set.all|length}}
      </div>
    </div>
  </div>
</div>

blog5/templates/blog5/modules/comment_form.html
{% load widget_tweaks %}

<div class="add-comment">
  <header>
    <h3 class="h6">コメント投稿</h3>
  </header>
  <form action="{% url 'blog5:comment' article.pk %}" class="commenting-form" method="POST">
    <div class="row">
      <div class="form-group col-md-6">
        {% render_field form.name class="form-control" placeholder="お名前" %}
        <!-- <input type="text" name="name" id="username" placeholder="名前" class="form-control"> -->
      </div>
      <div class="form-group col-md-6">
        {% render_field form.mailadress class="form-control" placeholder="メールアドレス(空欄可) / 一覧に表示はされません" %}
        <!-- <input type="email" name="mailadress" id="useremail" placeholder="メールアドレス（空欄可）" class="form-control"> -->
      </div>
      <div class="form-group col-md-12">
        {% render_field form.comment class="form-control" id="usercomment" placeholder="コメントを入力してください" rows="1" %}
      </div>
      <div class="form-group col-md-12">
        <button type="submit" class="btn btn-secondary">送信</button>
        {% csrf_token %}
      </div>
    </div>
  </form>
</div>

blog5/templates/blog5/modules/comments.html
<div class="post-comments">
  <header>
    <h3 class="h6">コメント一覧<span class="no-of-comments">({{ article.comment_set.all|length }})</span></h3>
  </header>
  <!-- コメント欄 -->
  {% for comment in article.comment_set.all %}
  <div class="comment">
    <div class="comment-header d-flex justify-content-between">
      <div class="user d-flex align-items-center">
        <div class="title"><strong>{{ comment.name }}</strong><span class="date">{{ comment.created_at }}</span></div>
      </div>
    </div>
    <div>
      <p>{{ comment.comment }}</p>
    </div>
    {% endfor %}
  </div>
</div>

blog5/templates/blog5/modules/current-post.html
<div class="blog-posts"><a href="{% url 'blog5:detail' current_article.pk %}">
    <div class="item d-flex align-items-center">
      <div class="image"><img src="{{ current_article.image.url }}" alt="..." class="img-fluid"></div>
      <div class="title"><strong>{{ current_article.title }}</strong>
        <div class="d-flex align-items-center">
          <div class="views">{{ current_article.created_at|date:"Y-m-j H:i:s" }}</div>
          <div class="comments"><i class="icon-comment"></i>{{ current_article.comment_set.all|length }}</div>
        </div>
      </div>
    </div></a>
  </div>

blog5/templates/blog5/modules/footer.html
<!-- Page Footer-->
<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="logo">
          <h6 class="text-white">Shunka's Blog</h6>
        </div>
        <div class="contact-details">
          <p>このブログはPythonとDjangoを<br>使って練習用に作りました。</p>
          <p>思い付きで更新します。（予定）</p>
          <ul class="social-menu">
            <li class="list-inline-item"><a href="https://www.facebook.com/shunsuke.shimizu.108" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="https://www.instagram.com/shunka4/" target="_blank"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="https://github.com/shunke434343" target="_blank"><i class="fa fa-github"></i></a></li>
            <li class="list-inline-item"><a href="https://shunke434343.github.io/" target="_blank"><i class="fa fa-home"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="menus d-flex">
          <ul class="list-unstyled">
          </ul>
          <ul class="list-unstyled">
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="latest-posts">
          <div class="post d-flex align-items-center">
            <!-- <div class="image"> -->
              <!-- <img src="img/small-thumbnail-1.jpg" alt="..." class="img-fluid"> -->
            <!-- </div> -->
            <div class="title"></div>
          </div>
          <div class="post d-flex align-items-center">
            <div class="title"></div>
          </div>
          <div class="post d-flex align-items-center">
            <div class="title"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2019. All rights reserved.</p>
        </div>
        <div class="col-md-6 text-right">
          <p>Template By <a href="https://bootstraptemple.co" class="text-white">Bootstrap Temple</a>
            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

blog5/templates/blog5/modules/header.html
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg" style="background-color:rgb(241, 241, 241)">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn"><i class="icon-close"></i></div>
        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
            <form action="#">
              <div class="form-group">
                <input type="search" name="search" id="search" placeholder="キーワード">
                <button type="submit" class="submit"><i class="icon-search-1"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <!-- Navbar Brand -->
        <a href="{% url 'blog5:index' %}" class="navbar-brand">
        <h3>Shunka's Blog<h3><h6 style="font-size:14px; font-weight:normal">Python/Djangoを使って作りました。</h6></a>
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <!-- <li class="nav-item"><a href="index.html" class="nav-link ">Home</a>
          </li> -->
          <li class="nav-item" style="font-size:14px">
          </li>
          <!-- <li class="nav-item"><a href="post.html" class="nav-link ">Post</a>
          </li> -->
          <!-- <li class="nav-item"><a href="#" class="nav-link ">Contact</a>
          </li> -->
        </ul>
        <!-- <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div> -->
        <!-- <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul> -->
      </div>
    </div>
  </nav>
</header>

blog5/templates/blog5/modules/mooving.html
<div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
  {% with next=article.get_next_by_created_at %}
    {% if next %}
      <a href="{% url 'blog5:detail' next.pk %}" class="prev-post text-left d-flex align-items-center">
        <div class="icon prev"><i class="fa fa-angle-left"></i></div>
        <div class="text"><strong class="text-primary">次の記事 </strong>
          <h6>{{ next.title }}</h6>
        </div>
      </a>
    {% else %}
      <div class="prev-post text-left d-flex align-items-center"></div>
    {% endif %}
  {% endwith %}

  {% with prev=article.get_previous_by_created_at %}
    {% if prev %}
      <a href="{% url 'blog5:detail' prev.pk %}" class="next-post text-right d-flex align-items-center justify-content-end">
        <div class="text"><strong class="text-primary">前の記事 </strong>
          <h6>{{ prev.title }}</h6>
        </div>
        <div class="icon next"><i class="fa fa-angle-right"></i></div>
      </a>
    {% else %}
      <div class="next-post text-right d-flex align-items-center justify-content-end"></div>
    {% endif %}
  {% endwith %}
</div>

blog5/templates/blog5/modules/paginate.html
<!-- Pagination -->
<nav aria-label="Page navigation example">
  <ul class="pagination pagination-template d-flex justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <li class="page-item"><a href="#!" class="page-link active">{{ num }}</a></li>
      {% else %}
        <li class="page-item"><a href="?page={{ num }}" class="page-link">{{ num }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
    {% endif %}

  </ul>
</nav>

blog5/templates/blog5/modules/slide.html
{% load static %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static "pics/mac.jpg" %}/800x400?auto=yes&bg=777&fg=555&text=First slide" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=666&fg=444&text=Second slide" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=555&fg=333&text=Third slide" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>